<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <title>Promises</title>
    <link rel="stylesheet" href="../base.css" />
  </head>

  <body>
    <script>
      function makePizza(toppings = []) {
        return (pizzaPromise = new Promise(function (resolve, reject) {
          //reject if people ask for pineapple on pizza
          if (toppings.includes("pineapple")) {
            reject("Serously? Get out! 🍍");
          }
          const amountOfTimeToBake = 500 + toppings.length * 200;
          //wait 1s for the pizza to cook
          setTimeout(function () {
            //when you're ready you can resolve this promise
            resolve(
              `Here is your pizza 🍕 with the toppings: ${toppings.join(", ")}`
            );
          }, amountOfTimeToBake);

          //if something went wrong you can reject the promise
        }));
      }

      // makePizza(['pepperoni'])
      // .then(function(pizza){
      //   console.log(pizza);
      //   return makePizza(['ham','cheese']);
      // })
      // .then(function(pizza){
      //   console.log(pizza)
      //   return makePizza(['hot peppers', 'onion', 'feta']);
      // })
      // .then(function(pizza){
      //   console.log(pizza)
      //   return makePizza(['pineapple']);
      // })
      // .then(function(pizza){
      //   console.log(pizza)
      //   return makePizza(['hot peppers', 'onion', 'feta','ham', 'cheese', 'tomatoes','sausage', 'mushrooms', 'basil']);
      // })
      // .then(pizza => {
      //   console.log('All done, here is your last pizza! ')
      //   console.log(pizza)
      // }).catch(handleError);

      //run them concurrenlty

      // const pizzaPromise1 = makePizza(['hot peppers', 'onion', 'feta']);
      // const pizzaPromise2 = makePizza(['hot peppers', 'onion', 'feta','ham', 'cheese', 'tomatoes','sausage', 'mushrooms', 'basil']);
      // const pizzaPromise3 = makePizza(['ham','cheese']);
      // const pizzaPromise4 = makePizza(['chicken, pineapple']);

      // const dinnerPromise = Promise.all([pizzaPromise1,pizzaPromise2, pizzaPromise3, pizzaPromise4]);
      // dinnerPromise.then(function(pizzas){
      //   //I'm destructuring the array pizzas in 3 variables where each one gets assigned to one item of the array
      //   const [hottie, garbagePail, hamAndCheese, denied] = pizzas;
      //   console.log(hottie, garbagePail,hamAndCheese, denied)
      // })

      // //Promise.race returns the promise that completes faster
      // const firstPizzaPromise = Promise.race([pizzaPromise1,pizzaPromise2, pizzaPromise3]);
      // firstPizzaPromise.then(pizza=>{
      //   console.log(`you must be hungry, here's the first one ready!`)
      //   console.log(pizza)
      // })

      function handleError(err) {
        console.error("Oh Noooo!");
        console.error(err);
      }

      makePizza(["cheese", "pineapple"])
        .then((pizza) => {
          console.log(pizza);
        })
        .catch(handleError);

      const p1 = makePizza(["pepperoni"]);
      const p2 = makePizza(["pineapple"]);

      //Promise.all breaks after the error is found, instead Promise.allSettled
      //executes all the promises and returns an array where it says if the
      //promise was fullfilled or rejected.
      const megaPromise = Promise.allSettled([p1, p2]);
      megaPromise.then((results) => {
        console.log(results);
      });
    </script>
  </body>
</html>
